FROM registry.access.redhat.com/ubi8/openjdk-8
USER jboss
WORKDIR /tmp/src/
COPY --chown=jboss:jboss pom.xml pom.xml
COPY --chown=jboss:jboss src src
RUN echo "$(pwd)"
RUN ls -altr /usr/local/s2i/assemble
RUN /usr/local/s2i/assemble

